# Generated by Django 2.1.2 on 2018-12-29 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name_plural': 'friends'},
        ),
        migrations.RemoveField(
            model_name='friends',
            name='body',
        ),
        migrations.AddField(
            model_name='friends',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='friends',
            name='line',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='friends',
            name='tempat_tanggal_lahir',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='comment',
            name='friend',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='friends.Friends'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
